Print descriptive error message on benchmark jobs (#1887)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/1887

Adding a more descriptive message to users in case main builds are broken. Benchmark runs for PRs compare with a baseline (based on main), so in case main is broken the benchmark regression test suite fails. Printing a more descriptive error message to alert users about what's happening, and asking them to rebase on a healthy main.

Differential Revision: D37508791

fbshipit-source-id: ebf7c4cb042194c632b2c5bcfa1962ad290149d4

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -235,7 +235,15 @@ jobs:
             export CCACHE_DIR=$(realpath .ccache)
             ccache -sz -M 5Gi
             source /opt/rh/gcc-toolset-9/enable
-            make benchmarks-basic-build NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8
+
+            # If benchmark build on main is broken, print a warning message and let the job fail.
+            make benchmarks-basic-build NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8 || ( \
+              echo -e "\n\n" \
+                      "=============================================================\n" \
+                      "Benchmark execution uses the main branch as the baseline,\n" \
+                      "but it looks like builds on main are broken.\n" \
+                      "Please rebase your PR once main is fixed to unblock this job.\n" \
+                      "=============================================================\n"; exit 1)
             ccache -s
           no_output_timeout: 1h
       - run:
