temporarily remove local fmt

diff --git a/.circleci/dist_compile.yml b/.circleci/dist_compile.yml
--- a/.circleci/dist_compile.yml
+++ b/.circleci/dist_compile.yml
@@ -72,6 +72,9 @@ commands:
             if [ -e /opt/rh/gcc-toolset-9/enable ]; then
               source /opt/rh/gcc-toolset-9/enable
             fi
+            if [ -z "$VELOX_DEPENDENCY_SOURCE"]; then
+              rm -rf /usr/local/include/fmt || echo "fmt not found"
+            fi
       - restore_cache:
           name: "Restore CCache Cache"
           keys:
@@ -247,6 +250,7 @@ jobs:
     executor: build
     environment:
       DuckDB_SOURCE: SYSTEM
+      folly_SOURCE: BUNDLED
     steps:
       - pre-steps
       - install-duckdb
@@ -461,6 +465,7 @@ jobs:
     environment:
       VELOX_DEPENDENCY_SOURCE: SYSTEM
       simdjson_SOURCE: BUNDLED
+      folly_SOURCE: BUNDLED
       DuckDB_SOURCE: BUNDLED
     steps:
       - fuzzer-run:
@@ -601,6 +606,8 @@ jobs:
 
   linux-pr-fuzzer-run:
     executor: build
+    environment:
+      folly_SOURCE: BUNDLED
     steps:
       - pre-steps
       - run:
