[Temp]

diff --git a/.github/workflows/linux-build.yml b/.github/workflows/linux-build.yml
--- a/.github/workflows/linux-build.yml
+++ b/.github/workflows/linux-build.yml
@@ -87,22 +87,26 @@ jobs:
             chmod +x ./${MINIO_BINARY}
             mv ./${MINIO_BINARY} /usr/local/bin/
           fi
-
       - name: Install Proxygen
         run: |
           FB_OS_VERSION="v2024.05.20.00"
-          PROXYGEN_BINARY="proxygen-${FB_OS_VERSION}.tar.gz"
+          PROXYGEN_BINARY="proxygen.tar.gz"
           if [ ! -f /usr/local/bin/${PROXYGEN_BINARY} ]; then
             wget https://github.com/facebook/proxygen/archive/refs/tags/${FB_OS_VERSION}.tar.gz -O ${PROXYGEN_BINARY}
             tar -xzf ${PROXYGEN_BINARY}
-            cd proxygen-${FB_OS_VERSION}
-            ./build.sh   # Assumes there's a build script or replace with the appropriate build command
-            chmod +x ./proxygen-${FB_OS_VERSION}
-            mv ./proxygen-${FB_OS_VERSION} /usr/local/bin/
+            
+            # Check the actual directory name after extraction
+            DIR_NAME=$(tar -tf ${PROXYGEN_BINARY} | head -1 | cut -f1 -d"/")
+            
+            cd ${DIR_NAME} || { echo "Directory ${DIR_NAME} not found"; exit 1; }
+            
+            ./build.sh   # Replace this with the correct build command if necessary
+            chmod +x ./proxygen
+            mv ./proxygen /usr/local/bin/
+            
             cd ..
-            rm -rf proxygen-${FB_OS_VERSION} ${PROXYGEN_BINARY}
+            rm -rf ${DIR_NAME} ${PROXYGEN_BINARY}
           fi
-
 
       - uses: assignUser/stash/restore@v1
         with:
