list missing dynamic libraries

diff --git a/.github/workflows/linux-build-base.yml b/.github/workflows/linux-build-base.yml
--- a/.github/workflows/linux-build-base.yml
+++ b/.github/workflows/linux-build-base.yml
@@ -269,16 +269,20 @@ jobs:
         with:
           name: cudftestbinaries
 
-      - name: Verify Download and Fix Absolute Paths
+      - name: Adapt Downloaded Files
         run: |
           ls -R .
+          # Change hardcoded workspace path in CTestTestfile.cmake to the runner workspace
           sed -i 's|/__w/velox/velox|${{ github.workspace }}|g' _build/release/velox/experimental/cudf/tests/CTestTestfile.cmake
-          cat _build/release/velox/experimental/cudf/tests/CTestTestfile.cmake
+          grep "Source directory" _build/release/velox/experimental/cudf/tests/CTestTestfile.cmake
+          grep "Build directory" _build/release/velox/experimental/cudf/tests/CTestTestfile.cmake
+          # Add execute permissions to the test file and check for missing dynamic libraries
+          chmod +x _build/release/velox/experimental/cudf/tests/velox_cudf*
+          MISSING=$(for exe in _build/release/velox/experimental/cudf/tests/*; do [ -x "$exe" ] && ldd "$exe" 2>/dev/null; done | grep "not found" | awk '{print $1}' | sort -u); if [ -n "$MISSING" ]; then echo "Missing libraries:"; echo "$MISSING"; exit 1; else echo "No missing libraries found"; fi
 
       - name: Run cuDF Tests
         run: |
           cd _build/release/velox/experimental/cudf/tests/
-          chmod +x velox_cudf*
           export DEPS_PATH=../../../../_deps/
           export LD_LIBRARY_PATH=$DEPS_PATH/cudf-build:$DEPS_PATH/rmm-build:$LD_LIBRARY_PATH
           export LD_LIBRARY_PATH=$DEPS_PATH/kvikio-build:$DEPS_PATH/curl-build:$LD_LIBRARY_PATH
