copy cudf test libs

diff --git a/.github/workflows/linux-build-base.yml b/.github/workflows/linux-build-base.yml
--- a/.github/workflows/linux-build-base.yml
+++ b/.github/workflows/linux-build-base.yml
@@ -236,7 +236,29 @@ jobs:
       - name: Copy Shared Libraries for cuDF Test Binaries
         if: ${{ ! inputs.use-clang && steps.changes.outputs.cudf && always() }}
         run: |
-          for exe in _build/release/velox/experimental/cudf/tests/velox_cudf_*; do ldd "$exe" 2>/dev/null; done | sed -n 's/''[^\/]*''\(\/[^ ]*\)'' .*''/\1/p' | sort -u || true
+          mkdir -p _build/release/cudf-libs
+          deps=$( \
+            for exe in _build/release/velox/experimental/cudf/tests/velox_cudf_*; \
+              do ldd "$exe" 2>/dev/null; done | \
+            sed -n 's/[^\/]*\(\/[^ ]*\) .*/\1/p' | \
+            # don't copy cuda libraries
+            sed '/libcuda/ d' | sort -u \
+          ) && \
+          # copy all "real" files and symlink targets to _build/release/cudf-libs
+          ( \
+            echo "$deps" | \
+            xargs readlink -f | \
+            xargs -I {} cp {} _build/release/cudf-libs/ \
+          ) && \
+          # filter out which libraries are symlinks
+          lndeps=$(echo "$deps" | xargs -I {} bash -c '[ -L "$1" ] && echo "$1" || true' bash {}) && \
+          # write new symlinks to the same folder, with targets in the same folder
+          ( \
+            cd _build/release/cudf-libs && \
+            echo "$lndeps" | \
+            xargs -I {} bash -c 'ln -s $(basename $(readlink -f "$1")) $(basename "$1")' bash {} \
+          )
+          tar -cvf _build/release/cudf-libs.tar _build/release/cudf-libs
 
       - name: Upload cuDF Test Binaries
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
@@ -248,6 +270,7 @@ jobs:
             velox/experimental/cudf/tests/CMakeLists.txt
             _build/release/velox/experimental/cudf/tests/velox_cudf_*
             _build/release/velox/experimental/cudf/tests/CTestTestfile.cmake
+            _build/release/cudf-libs.tar
           retention-days: ${{ env.RETENTION }}
 
   cudf-tests:
@@ -259,6 +282,7 @@ jobs:
       - name: Check NVIDIA Driver Version
         run: |
           nvidia-smi
+          ls /usr/local/cuda*
 
       - name: Install Packages
         run: sudo apt-get update && sudo apt-get install -y cmake
@@ -275,7 +299,14 @@ jobs:
           sed -i 's|/__w/velox/velox|${{ github.workspace }}|g' _build/release/velox/experimental/cudf/tests/CTestTestfile.cmake
           grep "Source directory" _build/release/velox/experimental/cudf/tests/CTestTestfile.cmake
           grep "Build directory" _build/release/velox/experimental/cudf/tests/CTestTestfile.cmake
-          MISSING=$(for exe in _build/release/velox/experimental/cudf/tests/velox_cudf_*; do ldd "$exe" 2>/dev/null; done | grep "not found" | awk '{print $1}' | sort -u); if [ -n "$MISSING" ]; then echo "Missing libraries:"; echo "$MISSING"; exit 1; else echo "No missing libraries found"; fi
+          tar -xvf _build/release/cudf-libs.tar -C _build/release/
+          export LD_LIBRARY_PATH="$PWD/_build/release/cudf-libs/:${LD_LIBRARY_PATH}"
+          echo $LD_LIBRARY_PATH
+          MISSING=$(for exe in _build/release/velox/experimental/cudf/tests/velox_cudf_*; \
+            do ldd "$exe" 2>/dev/null; done | \
+            grep "not found" | awk '{print $1}' | sort -u); \
+            if [ -n "$MISSING" ]; then echo "Missing libraries:"; echo "$MISSING"; exit 1; \
+            else echo "No missing libraries found"; fi
 
       - name: Run cuDF Tests
         run: |
